#app:
#  ntp-address: ntp1.dh-home.cn
#server:
#  port: 18151
#  servlet:
#  context-path: /bjhj
#spring:
#  datasource:
#    bjhj:
#      url: jdbc:mysql://10.10.10.20:3306/bjhj?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: bjhj_dml
#      password: bjhj_DML!@#4
#      driver-class-name: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 20
#      min-idle: 20
#      max-active: 200
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#
#    wh:
#      url: jdbc:mysql://rr-2zedcfyu32454ges9.mysql.rds.aliyuncs.com:3306/winghead?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: beijinghujin_ro
#      password: BJHJ_ro!+890
#      driver-class-name: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 20
#      min-idle: 20
#      max-active: 200
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#xxl:
#  job:
#    admin:
#      addresses: http://bjhj-upload.dh-home.cn/xxl
#    executor:
#      appname: bjhj
#      port: 8151
#      logpath: /tmp/bjhj/logs
#bihj:
#  user: dehongpuhui
#  pwd: dehongpuhui123
#  sourceCode: BJ20160831001
#  address: https://bjp2p.com.cn:8443/platformService
#  nameSpace: http://supervise.service.app.mp.zkbc.net/
#  submitThreadPool:
#    coreAndMaxPoolSize: 8
#    threadSleepMillis: 60000
#    queryBatchLimit: 1000
#    queueAccept: 3000
#    queueMaxSize: 10000
#huxie:
#  uploadUrl: http://huxie.dh-ali.cn/analyze/uploadApi #上报地址
#  saveCsvPath: /Public #csv保存地址
#
#
#
