#app:
#  ntp-address: ntp1.dh-home.cn
#server:
#  port: 18151
#  servlet:
#  context-path: /bigdata
#spring:
#  datasource:
#    bjhj:
#      url: jdbc:mysql://127.0.0.1:3306/bjhj?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 20
#      min-idle: 20
#      max-active: 50
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#    wh:
#      url: jdbc:mysql://172.16.12.8:3306/winghead?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      username: winghead_select
#      password: winghead_123456
#      driver-class-name: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 20
#      min-idle: 20
#      max-active: 200
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#xxl:
#  job:
#    admin:
#      addresses: http://test-job.dh-home.cn/
#    executor:
#      appname: bjhj
#      port: 8151
#      logpath: /tmp/bjhj/logs
#bihj:
#  user: dehongjr
#  pwd: dehongjr@123
#  sourceCode: BJ20171219002
#  address: https://test.bjp2p.com.cn:8443/platformService
#  nameSpace: http://supervise.service.app.mp.zkbc.net/
#  submitThreadPool:
#    coreAndMaxPoolSize: 8
#    threadSleepMillis: 60000
#    queryBatchLimit: 1000
#    queueAccept: 3000
#    queueMaxSize: 10000
#huxie:
#  uploadUrl: http://huxie.dh-ali.cn/analyze/uploadApi #上报地址
#  saveCsvPath: /Public #csv保存地址
#
#
#
#
#
